name: testing demo

on: 
  push:
    branches: 
    - main
  pull_request: 
    branches: 
    - pull-req-test

jobs:
  display:
    runs-on: ubuntu-latest

    steps:
      - name: checkingout repos
        uses: actions/checkout@v4

      - name: install python dependencies
        run: python -m testing.py 

      - name: display message 
        run: echo "testing done".
    
     

    

    
  
  

 
